apiVersion: apps/v1
kind: Deployment
metadata:
  name: wireguard
  namespace: wireguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wireguard
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wireguard
    spec:
      restartPolicy: Always
      # hostNetwork: true
      containers:
        - name: wireguard
          image: lscr.io/linuxserver/wireguard:latest
          env:
            - name: ALLOWEDIPS
              value: 0.0.0.0/0
            - name: INTERNAL_SUBNET
              value: 10.13.13.0
            - name: LOG_CONFS
              value: "true"
            - name: PEERDNS
              value: auto
            - name: PEERS
              value: "2"
            - name: PERSISTENTKEEPALIVE_PEERS
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: SERVERPORT
              value: "51820"
            - name: SERVERURL
              value: admin.thelegend27.fr
            - name: TZ
              value: Etc/UTC
          ports:
            - containerPort: 51820
              protocol: UDP
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE
          volumeMounts:
            - mountPath: /config
              name: wireguard-config
      volumes:
        - name: wireguard-config
          hostPath:
            path: /home/thelegend27/homeserver/wireguard/config
