#
# Traefik Forward Auth Deployment
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-forward-auth
  namespace: traefik
  labels:
    app: traefik-forward-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik-forward-auth
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: traefik-forward-auth
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: thomseddon/traefik-forward-auth:2
        name: traefik-forward-auth
        ports:
        - containerPort: 4181
          protocol: TCP
        env:
        - name: LOG_LEVEL
          value: trace
        # - name: DOMAIN
        #   value: admin.thelegend27.fr
        # INSECURE_COOKIE is required unless using https entrypoint
        # - name: INSECURE_COOKIE
        #   value: "true"
        - name: COOKIE_DOMAIN
          value: admin.thelegend27.fr
        - name: AUTH_HOST
          value: auth.admin.thelegend27.fr
        - name: DEFAULT_PROVIDER
          value: generic-oauth
        - name: WHITELIST
          valueFrom:
            secretKeyRef:
              name: traefik-forward-auth-secrets
              key: traefil-forward-auth-whitelist
        - name: PROVIDERS_GENERIC_OAUTH_AUTH_URL
          valueFrom:
            secretKeyRef:
              name: traefik-forward-auth-secrets
              key: traefik-forward-auth-github-auth-url
        - name: PROVIDERS_GENERIC_OAUTH_TOKEN_URL
          valueFrom:
            secretKeyRef:
              name: traefik-forward-auth-secrets
              key: traefik-forward-auth-github-token-url
        - name: PROVIDERS_GENERIC_OAUTH_USER_URL
          valueFrom:
            secretKeyRef:
              name: traefik-forward-auth-secrets
              key: traefik-forward-auth-github-user-url
        - name: PROVIDERS_GENERIC_OAUTH_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: traefik-forward-auth-secrets
              key: traefik-forward-auth-github-client-id
        - name: PROVIDERS_GENERIC_OAUTH_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: traefik-forward-auth-secrets
              key: traefik-forward-auth-github-client-secret

        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: traefik-forward-auth-secrets
              key: traefik-forward-auth-secret
---
#
# Auth Middleware
#
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-forward-auth
  namespace: traefik
spec:
  forwardAuth:
    address: http://traefik-forward-auth.traefik:4181
    authResponseHeaders:
      - X-Forwarded-User
