apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-forward-auth-ingress
  namespace: cert-manager
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`auth.admin.thelegend27.fr`)
      middlewares:
        - name: traefik-forward-auth
          namespace: traefik
      services:
        - name: traefik-forward-auth
          namespace: traefik
          port: 4181
  tls:
    secretName: wildcard-admin-thelegend27-tls
