apiVersion: v1
kind: Endpoints
metadata:
  name: glinet-router
  namespace: router
subsets:
  - addresses:
      - ip: 192.168.8.1
    ports:
      - port: 80
---
apiVersion: v1
kind: Endpoints
metadata:
  name: orange-router
  namespace: router
subsets:
  - addresses:
      - ip: 192.168.1.1
    ports:
      - port: 443
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: glinet-router
  namespace: router
addressType: IPv4
endpoints:
  - addresses:
      - 192.168.8.1
    conditions:
      ready: true
ports:
  - name: http
    port: 80
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: orange-router
  namespace: router
addressType: IPv4
endpoints:
  - addresses:
      - 192.168.1.1
    conditions:
      ready: true
ports:
  - name: https
    port: 443
