apiVersion: v1
kind: Endpoints
metadata:
  name: glinet-router
  namespace: router
subsets:
  - addresses:
      - ip: 192.168.8.1
    ports:
      - port: 80
---
apiVersion: v1
kind: Endpoints
metadata:
  name: orange-router
  namespace: router
subsets:
  - addresses:
      - ip: 192.168.1.1
    ports:
      - port: 443
