kind: Service
apiVersion: v1
metadata:
  name: pihole-dns
  namespace: pihole
spec:
  type: LoadBalancer
  selector:
    app: pihole
  ports:
    - port: 53
      targetPort: 53
      name: pihole-dns-udp
      protocol: UDP
    - port: 53
      targetPort: 53
      name: pihole-dns-tcp
      protocol: TCP
    - port: 67
      targetPort: 67
      name: pihole-67-udp
      protocol: UDP
---
kind: Service
apiVersion: v1
metadata:
  name: pihole-web
  namespace: pihole
spec:
  type: LoadBalancer
  selector:
    app: pihole
  ports:
    - port: 8080
      targetPort: 80
      name: http
    - port: 8443
      targetPort: 443
      name: https
