apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pihole-ingress
  namespace: cert-manager
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`pihole.admin.thelegend27.fr`)
      middlewares:
        - name: traefik-forward-auth
          namespace: traefik
      services:
        - name:  pihole-web
          namespace: pihole
          port: 8080

  tls:
    secretName: admin-thelegend27-tls
