apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minecraft
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/Thomas141100/homeserver.git'
      path: kubernetes/minecraft
      targetRevision: lenovotiny
      ref: values
    - repoURL: https://itzg.github.io/minecraft-server-charts/
      chart: minecraft
      targetRevision: 5.0.0
      helm:
        valueFiles:
          - $values/kubernetes/minecraft/values.yaml
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  destination:
    server: https://kubernetes.default.svc
    namespace: minecraft
