---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minecraft-data
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /mnt/media/minecraft
  storageClassName: hostpath
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
